# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

name: Release Branch Checks
on:
  push:
    branches:
      - 'release/*'

jobs:
  version:
    name: Check version number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java/Maven
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: maven
      - name: Get version from POM
        id: get-version
        run: echo project_version=$(./mvnw $MAVEN_CLI_OPTS help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT
      - name: Validate Version Format (Semantic Versioning)
        run: |
          if [[ ! "${{ steps.get-version.outputs.project_version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Invalid version format! Expected X.Y.Z (e.g., 1.2.3)"
            exit 1
          fi
      - name: Check version matches branch
        run: |
          echo "Checking that ${GITHUB_REF} matches refs/heads/release/${{ steps.get-version.outputs.project_version }}"
          if [[ "${GITHUB_REF}" != "refs/heads/release/${{ steps.get-version.outputs.project_version }}" ]]; then
              echo "❌ Version number does not match branch name"
              exit 1
          fi
